import turtle
import turtle as t
t.color("red","red")
t.begin_fill()
t.fd(300)
t.left(90)
t.fd(165)
t.left(90)
t.fd(300)
t.left(90)
t.fd(165)
t.left(90)
t.fd(300)
t.end_fill()
t.penup()
t.color("yellow","yellow")
t.left(160)
t.fd(250)
t.pendown()
t.begin_fill()
for i in range(5):
    t.forward(60)
    t.right(144)
t.end_fill()
t.penup()
t.right(144)
t.fd(35)
t.pendown()
t.begin_fill()
for i in range(5):
    t.forward(15)
    t.right(144)
t.end_fill()
t.penup()
t.left(90)
t.fd(10)
t.pendown()
t.begin_fill()
for i in range(5):
    t.forward(15)
    t.right(144)
t.end_fill()
t.penup()
t.left(15)
t.fd(15)
t.pendown()
t.begin_fill()
for i in range(5):
    t.forward(15)
    t.right(144)
t.end_fill()
t.penup()
t.left(10)
t.fd(20)
t.pendown()
t.begin_fill()
for i in range(5):
    t.forward(15)
    t.right(144)
t.end_fill()
