import turtle
import turtle as t
t.setup(650,350,200,200)
t.penup()
t.fd(-100)
t.pendown()
t.pensize(20)
t.pencolor("violet")
t.seth(-40)
for i in range (3):
    t.circle(40,80)
    t.penup()
    t.pendown()
    t.pencolor("yellow")
    t.circle(-40,80)
    t.penup()
    t.pendown()
    t.pencolor("red")
t.circle(40,80/2)
t.fd(40)
t.penup()
t.pendown()
t.pencolor("blue")
t.circle(16,160)
t.fd(60)
